.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

stages:
  - build
  - deploy

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
    - powershell ".\winbuild.ps1"
  artifacts:
    paths:
      - exec

pages:
  image: alpine:latest
  stage: deploy
  script: 
  - echo 'Building pages'
  artifacts:
    paths:
      - public
